version: '3'
services:
    
  postgres:
    image: postgres:13.1
    container_name: postgres
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ""
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.7.8
    container_name: adminer
    ports:
      - "9000:9000"
    depends_on:
      - postgres

volumes:
  database:

